### ISSUE TITLE
[FEATURE] Make icons.js usable in SFUI based projects

### ISSUE THREAD

**Issue by aniamusial** [vuestorefront/storefront-ui#1107]
**Describe how this feature will help us improve**

As a user I would love to simply use path names for icons instead of keeping them in assets. 
We should add possibility to override the icons.js file with custom icons.

**Comment by bkarlson** [comment]
+1 this, seems like icons js is a massive bloat for those using 1-2 icons only or switching to exernal icons libs.

**Comment by bkarlson** [comment]
at least consider passing all SVG thru SVGO, as looks like many are unoptimised and can take less space.

**Comment by martaradziszewska** [comment]
@EduardDopler I think we need you on this, can you help? :)

**Comment by EduardDopler** [comment]
Hey @martaradziszewska ! Great idea to tackle this 💪

I see two tasks here:
1. Optimize the SVGs, e.g. via [SVGOMG](https://jakearchibald.github.io/svgomg/)
2. Come up with some kind of a tree-shakeable "icon pack".

Concerning the 2nd part, I'll try to put some thought into it and experiment with what webpack makes out of it. I'll come back to you as soon as I have something.

I've just noticed that this is labeled important – is it urgent, too?

**Comment by martaradziszewska** [comment]
@EduardDopler it is an important issue but I think we have still some time to work on it to do it in the best way :) @pspaczek, please back me up here :) 

@EduardDopler I have been working on it and I have similar thoughts - for now, I split icons.js into separate js files and want to import each icon when its called. I succeeded with the `try...catch` method but I don't like it very much. Still missing idea how to get all file names to have some object with available icons - this can be useful. Waiting for your response in this matter :)

**Comment by EduardDopler** [comment]
@martaradziszewska So I tried the tree-shaking. To reiterate: I wanted that only those icons land in the final bundle which are actually used, i.e. are referenced in the SfIcon component.
Sadly, that didn't work and I came to the conclusion that it _cannot_ work. Here's why: The way we allow the users to choose icons from our icon pack (icons.js) is fully dynamic. The beauty and ease of use of a simple `<SfIcon icon="home" />` becomes a problem because that `"home"` is so dynamic that it could be populated in any possible way (e.g. via live end user input). Hence we have no way of knowing which icons we should include in the final bundle.

Or am I missing something?

**Comment by EduardDopler** [comment]
*bump*

A common approach is to use real files (_home.svg_, _heart.svg_, etc.) and store only the metadata inside JS. So the _icons.js_ would only contain the size information and the file names. 

From a performance perspective this would
- 📈 **increase** Time-to-last-byte (TTLB; though only on first visit, then it's cached) and Total-asset-count (insignificant for http/2) but
- 📉 **decrease** overall weight of the page and all first-paint and all delay metrics (FMP, FCP, FID, TTI, …) because the main bundle file gets smaller. Plus, compilation gets a bit faster.

As the metadata (like icons size) is rendered to HTML by Vue directly there shouldn't be any layout shift (CLS).

**Comment by EduardDopler** [comment]
In any way, we should optimize the SVG data and, as mentioned above, I had good outcomes with SVGOMG.

**Comment by gibkigonzo** [comment]
> Sadly, that didn't work and I came to the conclusion that it cannot work. Here's why: The way we allow the users to choose icons from our icon pack (icons.js) is fully dynamic. The beauty and ease of use of a simple <SfIcon icon="home" /> becomes a problem because that "home" is so dynamic that it could be populated in any possible way (e.g. via live end user input). Hence we have no way of knowing which icons we should include in the final bundle.
Or am I missing something?

@EduardDopler It would be nice if we can somehow disable loading icons at all and just import only needed icons in component. (in vuetify you can do that by setting config, but here we don't have config). Other option is to make some webpack loader for sfui :thinking: Last option is to make b/c and force to import icons by default, but this sucks :D 
```
<SfIcon :icon="add_to_cart" />
...
import {add_to_cart} from "@storefront-ui/shared/icons/icons";
```

SfIcon weights almost 30kb and I think that most projects don't use all of those icons.
