### ISSUE TITLE
[RFC] Styleguide

### ISSUE THREAD

**Issue by filrak** [vuestorefront/storefront-ui#1273]
After discussions on Discord and chats + https://github.com/DivanteLtd/storefront-ui/pull/1250/files I suggest doing the following with our new Styleguide:

- We use CSS vars only for global properties (like @EduardDopler suggested) and we try to keep their # as minimal as possible (atm only styleguide)
- We add utility classes for all global styles in designs. ( https://www.figma.com/file/N0Ct95cSAoODNv7zYS01ng/Storefront-UI-%7C-Design-System?node-id=0%3A1 ) - typo, colors, shadows, spacing
- We will add postfixes for breakpoint utility classes - `--s` `--t` `--d` for smartphone tablet and desktop, no prefix means all breakpoints (eg `text-base` vs `text-base--t`. For example `pd--s` (please mind double hyphen). To discuss if we want another breakpoint for laptops
- We use size gradation like in spacings (`xs` `sm` `base`  `lg` `xl`) **and we keep it consistent everywhere** (icons, utility classes, css vars)
- We use `primary` `secondary`, convention for fonts
- We use `x` `no-x` convention for boolean styles (like `shadow` `no-shadow`)
- We don't want to have a full set of all utility classes. If someone needs that they can use tailwind. What we should provide is ability to apply library-specific styles to components.
- CSS vars should be possibly descriptive, utility classes should be possibly short (but still descriptive)
Below my suggestions for specific classes. There is a high chance I overlooked something ;)

## General 

**Variables**
- `breakpoint--smartphone` `breakpoint--tablet` `breakpoint--desktop`

**Utilities**
- `hidden` + all breakpoints (for example `hidden--s`
- `visible` (like above)

Im not sure if DX here is intuitive.  For example to have something visible only for desktop you will use `hidden visible--d`
Alternatively we could have `smartphone-only` `tablet-only` `desktop-only` - WDYT?

## Typography
 
**Variables**
- `font-size--sm` `font-size--base` `font-size--lg` (talking with Marcin about adding more sizes to be also used in headings)
- `font-family--primary` `font-family--secondary`

Anything else here? Weights? Line heights? Should that be configured through vars?

**Utilities**
- `text-sm` `text-base` `text-lg` 
- `font-primary` `font-secondary`
- `h1` `h2` `h3` `h4` `h5` `h6`

## Colors
Convention for configurable colors will be `primary` `secondary` `info` `error` `alert` `success``(I'm open for keeping current `warning` `danger` `success` `info` , let me know about your opinion)

**Variables**
- Configurable `color--primary` `color--secondary` `color--info` `color--error` `color--alert` `
- Supportive `color--red` `color--blue` etc (for all colors in styleguide)

**Utilities**
- `c-primary` `c-secondary` `c-info` `c-error` `c-alert`
- `bg-primary` (etc)
- `text-primary` (could be misleading with `font-primary` refering to `font-family`?)

## Spacings

**Variables**
- like right now 

**Utilities**
- padding `pd-sm` `pd-base` `pd-lg` etc (to match spacings)
- margin like padding but with `mg`

## Shadows

TBD, @justyna-13 will propose naming ;)

My suggestion is to have

**Variables**
- `shadow`

**Utilities**
- `shadow` `no-shadow`

Please LMK WDYT about this naming convention and generally idea ;)

**Comment by justyna-13** [comment]
Great work @filrak! I have just some suggestions for utilities in typography: ```text-sm``` ```text-base``` ```text-lg``` exist already in tailwind, so that my proposition is to use ```txt-sm``` ```txt-base``` ```txt-lg``` :) and general utilities ```hidden``` and ```visible``` that also are in tailwind so maybe we could use  ```hidden--all```  and ```visible--all```? what do you think about it?  :)

**Comment by filrak** [comment]
We decided to 
- go with `txt` instead of `text`
- for breakpoints we will use utilities `smarphone-only` `tablet-only `desktop-only`
- for `left `right` etc in padding margins we write it without `-` (eg `pdx` `pdy` `pdl`)

**Comment by AdamPawlinski** [comment]
Wow, it looks completely different and nicer in case of DX. Idea to be complementary to tailwind is great. 
Few questions: 
- do we keep smallest and greatest size gradation like 2xs and 2xl and 3xl? In my opinion we should keep only these few basic sizes (xs sm base lg xl) and let people use other freely. We have adjusted these to use in our design which is not necessary the case in which other will use SFUI.
- there should be also utility classes for font-weight e.g. font-w-light, font-w-normal, font-w-bold
- for text colors, maybe it could be good to use text-c-primary convention because it will be more meaningful 
- in case of colors I would replace c-error with c-warning and c-danger like it is already implemented, because it is more universal (these colors not always need to mean error) and I wonder if adding lighten and darken version of each color like so c-warning--ligthen would be useful, wdyt?

**Comment by AdamPawlinski** [comment]
Comments on using utility classes in SFUI:

- there should be possibility to add paddings and margins for all screen sizes without adding --d, --t, --s
- it would be more clear if names of paddings and margins was divided with hyphen like so: “mry-lg” instead “mrylg” 
- paddings and margins should have 0 values
- in my opinion, we should add “transparent” to color palette 
- if we want utility class to be short and meaningful we should try to shorten color names: “txt-color-dark-secondary” is definitely  too long, how about sth like this txt-clr-dk-secondary

General conclusions:

- utility classes in current shape have very limited usage because they cannot be used in different states and css modifiers, so there should be some kind of @apply function like in tailwind which helps us to do it 
- adding utility classes is helpful for us as contributors in SFUI, but if I were developer I would most likely use tailwind together with SFUI, because it is well known and has much more features, 
- as a final conclusion I would propose two directions: 
- we can use utility classes but whole bunch of them must be wider and than more helpful (or just accept tailwind inside SFUI which should be only available as option)
- or we can stick to using custom properties, but need to find solution for comfortable overriding nested classes (e.g. override or nested custom properties in parent components) and help using them more easily by preparing VScode extension 

Please leave your comments @justyna-13 @Michal-Dziedzinski

**Comment by justyna-13** [comment]
I agree with you @AdamPawlinski. The only thing that had been discussed before and I forgot about it is the first point regarding padding and margins for all screen sizes - my PR has been corrected and now it contains mixin for this.

**Comment by filrak** [comment]
update - we will stick only to CSS vars

**Comment by dt2patel** [comment]
If this ticket isn't being actively worked on, this seems really interesting and I'd like to take a swing at it. We actually started something something similar at a theme level in this but haven't found time to complete it. It def makes much more sense at a framework level. [PR](https://github.com/vuestorefront/vsf-capybara/pull/596/files)
