### ISSUE TITLE
[BUG] error in SfTextarea story

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1619]
**Describe the bug**
Error showing in SfTextarea when trying to type something.

**How to reproduce**
Go to SfTextarea on Storybook and try to write down something. 

**Expected behavior**
No error.

**Actual behavior**

**Code examples**

**Screenshots**
![image](https://user-images.githubusercontent.com/32042425/104712834-5c5cf580-5723-11eb-8f41-e0d30e6b5603.png)

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

**Comment by mayashavin** [comment]
Two issues here to adjust:
1. `listeners.input && listeners.input()` is not a good code.
2. If we want to bind all listeners, we should use `v-bind` instead. Otherwise, use `$emit` as a safer approach.
3. There is an issue when out of focus a filled SfTextArea. (see image below)
![Screen Shot 2021-01-17 at 10 34 34](https://user-images.githubusercontent.com/6650139/104835562-2c8f2880-58b0-11eb-87db-a48ee422834f.png)
@AdamPawlinski

**Comment by AdamPawlinski** [comment]
I think we cannot use $emit in functional component as it has no context so I'm looking for another solution. If you have any idea please give me a hand :)

**Comment by AdamPawlinski** [comment]
I couldn't solve the problem with emitting input event value from functional component so changed SfTextarea back to normal component.
