### ISSUE TITLE
[FEAT] SfAccordeon should have opened items by default and work with JS disabled.

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/storefront-ui#1668]
**Describe how this feature will help us improve**
SfAccordeon should have opened items by default, and it should work properly without using js. It could be helpful for performance improvement. 

**Is your proposal related to a problem?**
SfAccordeon is closed when there is JS turned off. 
![image](https://user-images.githubusercontent.com/32042425/105760970-c6ab3c80-5f52-11eb-96e8-dda5fb6593cf.png)

**Describe the solution you'd considered**
Refactor SfAccordeon to have opened items by default. 

If there are multiple solutions, please present each one separately. Save comparisons for the very end.

**Additional context**
Anything you would like to add but was not sure which section it fits.

**Comment by Baroshem** [comment]
@AdamPawlinski I would need some explanation for this issue. Is the problem caused by the fact of disabling JavaScript in your browser or by initially setting `isOpen` data property in Accordion Item component to `false`? 
```js
  data() {
    return {
      isOpen: false,
    };
  },
```

In the issue title as well as the description there is no information about disabling JS, but it is mentioned in the related problem section. It's a bit confusing for me ;)

**Comment by AdamPawlinski** [comment]
The issue was initiated by @filrak in order to make this component work without any js. It should work only by using css, what can also improve our performance indicators. This title could be misleading in fact so I'll change it.

**Comment by AdamPawlinski** [comment]
It's connected with another issue [[BUG] SfFooter not working without JS #1667,](https://github.com/vuestorefront/storefront-ui/issues/1667) also with impact on performance.

**Comment by aniamusial** [comment]
to be implemented in SFUI2.0

**Comment by kasperstorgaard** [comment]
Not sure where this works is/will be happening, but here is a suggestion for v2:

I had to implement our own accordion instead of using SfAccordion to solve this issue, and ended up with a `<details><summary>` solution based on this article.
https://css-tricks.com/how-to-animate-the-details-element-using-waapi/

Support for `<details>` is excellent, and it seems all previous a11y issues are resolved.
The article above outlines a js based animation solution as a progressive enhancement.
