### ISSUE TITLE
[BUG] Cannot enter year manualy on <SfInput type="date"/>

### ISSUE THREAD

**Issue by SikoraWojciech** [vuestorefront/storefront-ui#1677]
**Describe the bug**
I cannot type year manually in ```<SfInput type="date"/>```, I can use keyboard arrows to increment/decrement year but when I'm trying to type "2021" I'm receiving "0001" or "0002" (it's switching between this values on each keydown).
Date picker is working, also I can set this date from code. I just cannot enter it with keyboard.

**How to reproduce**
1. Create ```<SfInput type="date"/>``` component
2. Focus it and set day and month manually
3. Try to type 2021 as YYYY

**Expected behavior**
I'm expecting that typing 2021 would set a year in this date to 2021.

**Actual behavior**
Year in my date is set to 0001 after typing 2021.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
<SfInput
  v-model="birthDate"
  name="birthDate"
  type="date"
  :label="$t('Birth date')"
/>
```

**Devices (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Google Chrome v88.0.4324.146

**Additional context**
This is behaving the same way on the docs https://docs.storefrontui.io/?path=/story/components-atoms-input--common
Just change type to date.

**Comment by AdamPawlinski** [comment]
@SikoraWojciech Thanks for reporting it. Would you like to make the PR for that?

**Comment by sderoij** [comment]
Hi all,

This seems to be happening due to a keyHandler in the focus-directive.js file that reapplies focus to the element (thus resetting the progress on the year input).

`el._keyHandler = function () {
  el.style.outline = "";
  el.focus();
};`

Preventing this handler on any other key than the Tab key (based on the explanation for the bind method in https://blog.vuestorefront.io/how-storefront-ui-solves-website-accessibility-issues/) seems to resolve the issue.

**Comment by Baroshem** [comment]
Hi @sderoij,

Thanks for reaching. As you already managed to find a potential solution to the problem, maybe you could create a pull request? 😃

**Comment by sderoij** [comment]
Hi @Baroshem,

See the PR above! Have a nice day :)

**Comment by Baroshem** [comment]
@sderoij 

I merged your Pull Request. Well done!
