### ISSUE TITLE
[FEATURE] clean up Storybook docs

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/storefront-ui#1906]
**Describe how this feature will help us improve**
Describe why do you think this feature is needed. 

Currently our docs are pretty messed up. We have mixed docs with components, there are a lot of information at the top that might not be used by developers, and so on. I would recommend implementing these changes in order to make our docs more readable and easier to use.

1. (To do after #1904 ) move examples (Cart.vue and Form.vue) to templates in components section
2. Move releases section to the bottom of the Storybook sidebar
3. Move pages to the section of components (then we would have clean atoms -> molecules -> organisms -> templates -> pages)
4. Add colors and typography to development section
5. Rename templates section with default to layouts
6. Group CSS Customization, Pull of Components, Local Development, Colors, Typography, FAQ into one folder called `Development guide`
7. Move Design Principles and Team to the section with Welcome and Who is using Storefront UI
8. Move Contributing Guide to Setup
9. Rename Setup to Getting Started

So our final sidebar should look like this
```
Welcome
Who is Using Storefront UI?
Design Principles
Team

**Getting Started**
  - Installation
  - Development Guide
    - CSS Customization
    - Local Development
    - Pull of components
    - Colors
    - Typography
    - FAQ
  - Contributing Guide

**Components**
  - Atoms
  - Molecules
  - Organisms
  - Templates
  - Pages

**Layouts**
  - Default 

**Utilities**
  - Transitions

**Releases**
  - List of releases ...
```

**Comment by AdamPawlinski** [comment]
ad 1 totally agree,
ad 2 I think this one is important we can leave it, but maybe accordion should be closed, wdyt?
ad 3 it should be together with other components, but the name will be misleading. I propose 'elements' or 'component levels' because that is how it is named here https://bradfrost.com/blog/post/atomic-web-design/ 
ad 4 agree
ad 5 agree 
ad 6 agree 
ad 7 agree 
ad 8 I think this one should be separate and be in root, because contributors should find this easily  
ad 9 agree

**Comment by justyna-13** [comment]
1. Ok
2. Agree with Adam 
3. Ok
4. Ok
5. Ok
6. Ok
7. Ok
8. Agree with Adam
9. Ok
