### ISSUE TITLE
[BUG] Storybook Accessibility Focus is not following keyboard using screen reader

### ISSUE THREAD

**Issue by MaciejWolowski** [vuestorefront/storefront-ui#2408]
**Describe the bug**
Checking storybook accessibility using screen reader, focus is not following keyboard actions but screen reader is reading next objects

**Preconditions**

* Some screen reader installed, I was using NVDA

**How to reproduce**

1. Go to Storybook
1. Open Screen Reader (reproduced using nvda)
1. Start using "Tab" for checking focus on the website
1. Move Focus for example to Releases
1. Wait until screen reader reads Releases
1. Using Keyboard arrows go bottom through the versions

**Expected behavior**
Both Focus shows next objects and screen reader reads it.

**Actual behavior**
Focus stays on Releases but screen reader reads next versions with your clicking the keyboard arrows

**Screenshots**
![Storybook Accessibility Focus is not following keyboard](https://user-images.githubusercontent.com/103260041/168257948-fc4c69cb-fc0a-4f05-bf3d-bd41e011d046.png)

**Devices (please complete the following information):**

* Device: [Desktop]
* OS: [Windows 11]
* Browser: [Chrome]

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/SFUI-146) by [Unito](https://www.unito.io)

**Comment by AdamPawlinski** [comment]
The problem with a11y of folders in sidebar is probably on Storybook side. There issues with:
-  `aria-expanded` https://github.com/storybookjs/storybook/issues/18346 
- and in my opinion `tabindex` of buttons inside folders have wrong value, there should be `0` instead of `-1`.
But anyway it is not the issue that we can manage. If that's okay for you @MaciejWolowski I will close it?

**Comment by MaciejWolowski** [comment]
@AdamPawlinski ok
