### ISSUE TITLE
ProductCard block - the product information should be in a variable and not hard-coded in template

### ISSUE THREAD

**Issue by mayashavin** [vuestorefront/storefront-ui#2647]
### Provide a description of requested docs changes

The code example currently have all the sample product's information hard-coded within the template, making it's hard to customize when copy/past-ing to user's codebase.

Solution: Wrap them into a variable `product` in <script>

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkacper** [comment]
Thank you for bringing this topic up @mayashavin. We decided to hard-code all the content because we don't want to impose any data shape. We want users to decide what data they want to put in a particular place. What we provide is just a proposition of they could do. However, we appreciate your input and we may reconsider if this approach is as smooth as we think.
